import: definition.yaml

concurrency:
  task:
    medagentbench-std: 20
  agent:
    claude-3.5-sonnet-v2: 5
    gpt-5.2: 5
    deepseek-v3: 5
    gemini-1.5-pro: 5

assignments:
  - agent:
      - claude-3.5-sonnet-v2
      - gpt-5.2
      - deepseek-v3
      - gemini-1.5-pro
    task:
      - medagentbench-std

output: "outputs/clinKriya-benchmark"
