"""
Rollout collection for GRPO training.

Runs complete episodes using the policy model and environment, collecting
trajectories with per-turn log probabilities for policy gradient updates.

Key concepts:
  - A Trajectory is one complete episode: a sequence of (state, action, reward) tuples
  - A RolloutGroup is K trajectories for the same task (for GRPO advantage computation)
  - collect_rollout() runs one episode end-to-end
  - collect_group_rollouts() runs K episodes for GRPO
"""

from __future__ import annotations

import json
import time
from dataclasses import dataclass, field
from typing import Optional, TYPE_CHECKING

from .config import RLConfig
from .env import MedAgentEnv
from .reward import EpisodeRewards
from .tool_parser import ParsedToolCall

if TYPE_CHECKING:
    from .policy import PolicyModel


# ─── Data structures ────────────────────────────────────────────────────────


@dataclass
class TurnRecord:
    """One assistant turn in the episode."""
    step: int
    messages_before: list[dict]       # conversation context (input to LLM)
    assistant_response: dict          # {"content": ..., "tool_calls": [...]}
    generated_text: str               # raw text generated by the model
    token_ids: list[int] = field(default_factory=list)  # generated token IDs
    log_probs: list[float] = field(default_factory=list)  # per-token log probs
    step_reward: float = 0.0


@dataclass
class Trajectory:
    """One complete episode trajectory."""
    task_id: str
    task: dict
    turns: list[TurnRecord] = field(default_factory=list)
    total_reward: float = 0.0
    terminal_pass: bool = False
    episode_rewards: Optional[dict] = None
    duration_seconds: float = 0.0

    @property
    def num_turns(self) -> int:
        return len(self.turns)

    @property
    def all_token_ids(self) -> list[int]:
        """Flatten all generated token IDs across turns."""
        ids = []
        for turn in self.turns:
            ids.extend(turn.token_ids)
        return ids

    @property
    def all_log_probs(self) -> list[float]:
        """Flatten all per-token log probs across turns."""
        lps = []
        for turn in self.turns:
            lps.extend(turn.log_probs)
        return lps


@dataclass
class RolloutGroup:
    """K trajectories for the same task (for GRPO advantage computation)."""
    task_id: str
    trajectories: list[Trajectory] = field(default_factory=list)

    @property
    def rewards(self) -> list[float]:
        return [t.total_reward for t in self.trajectories]

    @property
    def mean_reward(self) -> float:
        r = self.rewards
        return sum(r) / len(r) if r else 0.0

    @property
    def std_reward(self) -> float:
        r = self.rewards
        if len(r) <= 1:
            return 1.0
        mean = self.mean_reward
        variance = sum((x - mean) ** 2 for x in r) / len(r)
        return max(variance ** 0.5, 1e-8)

    def compute_advantages(self, eps: float = 1e-8) -> list[float]:
        """GRPO advantage: A_k = (r_k - mean(r)) / (std(r) + eps)."""
        mean = self.mean_reward
        std = self.std_reward
        return [(r - mean) / (std + eps) for r in self.rewards]


# ─── Rollout collection ────────────────────────────────────────────────────


def collect_rollout(
    env: MedAgentEnv,
    policy: "PolicyModel",
    task_id: Optional[str] = None,
    verbose: bool = False,
) -> Trajectory:
    """
    Run one complete episode using the policy and environment.

    Args:
        env: The MedAgentEnv environment
        policy: The PolicyModel that generates actions
        task_id: Specific task to use (or None for random)
        verbose: Print step info

    Returns:
        A Trajectory containing all turns, rewards, and log probs
    """
    start_time = time.time()

    # Reset environment
    options = {"task_id": task_id} if task_id else {}
    obs, info = env.reset(options=options)

    trajectory = Trajectory(
        task_id=info["task_id"],
        task=obs["task"],
    )

    terminated = False
    truncated = False

    while not (terminated or truncated):
        step = obs["step"]
        messages = obs["messages"]
        tool_schemas = obs["tool_schemas"]

        # Generate action with the policy
        response = policy.generate(
            messages=messages,
            tools=tool_schemas,
        )

        # Record the turn
        turn = TurnRecord(
            step=step,
            messages_before=messages.copy(),
            assistant_response=response["action"],
            generated_text=response.get("generated_text", ""),
            token_ids=response.get("token_ids", []),
            log_probs=response.get("log_probs", []),
        )

        # Step the environment
        obs, reward, terminated, truncated, info = env.step(response["action"])
        turn.step_reward = reward
        trajectory.turns.append(turn)

        if verbose:
            print(
                f"  Turn {step}: reward={reward:+.3f}  "
                f"terminated={terminated}  truncated={truncated}"
            )

    # Finalise trajectory
    trajectory.total_reward = sum(t.step_reward for t in trajectory.turns)
    trajectory.terminal_pass = info.get("terminal_pass", False)
    trajectory.episode_rewards = info.get("episode_rewards")
    trajectory.duration_seconds = time.time() - start_time

    if verbose:
        status = "✓ PASS" if trajectory.terminal_pass else "✗ FAIL"
        print(
            f"  Episode done: {status}  total_reward={trajectory.total_reward:.3f}  "
            f"turns={trajectory.num_turns}  time={trajectory.duration_seconds:.1f}s"
        )

    return trajectory


def collect_group_rollouts(
    env: MedAgentEnv,
    policy: "PolicyModel",
    task_id: str,
    group_size: int = 4,
    verbose: bool = False,
) -> RolloutGroup:
    """
    Collect K rollouts for the same task (for GRPO).

    Args:
        env: The MedAgentEnv environment
        policy: The PolicyModel
        task_id: Task ID to run
        group_size: Number of rollouts (K)
        verbose: Print info

    Returns:
        A RolloutGroup with K trajectories and computed advantages
    """
    group = RolloutGroup(task_id=task_id)

    for k in range(group_size):
        if verbose:
            print(f"\n  --- Rollout {k+1}/{group_size} for {task_id} ---")

        trajectory = collect_rollout(
            env=env,
            policy=policy,
            task_id=task_id,
            verbose=verbose,
        )
        group.trajectories.append(trajectory)

    if verbose:
        advantages = group.compute_advantages()
        print(f"\n  Group rewards: {group.rewards}")
        print(f"  Group advantages: {[f'{a:.3f}' for a in advantages]}")
        print(f"  Mean reward: {group.mean_reward:.3f}")

    return group


def collect_epoch_rollouts(
    env: MedAgentEnv,
    policy: "PolicyModel",
    task_ids: list[str],
    group_size: int = 4,
    verbose: bool = False,
) -> list[RolloutGroup]:
    """
    Collect rollout groups for all tasks in an epoch.

    Args:
        env: The MedAgentEnv environment
        policy: The PolicyModel
        task_ids: Task IDs to use for this epoch
        group_size: Rollouts per task (K)
        verbose: Print info

    Returns:
        List of RolloutGroups, one per task
    """
    groups = []

    for i, task_id in enumerate(task_ids):
        if verbose:
            print(f"\n{'='*50}")
            print(f"  Task {i+1}/{len(task_ids)}: {task_id}")
            print(f"{'='*50}")

        group = collect_group_rollouts(
            env=env,
            policy=policy,
            task_id=task_id,
            group_size=group_size,
            verbose=verbose,
        )
        groups.append(group)

    return groups
